# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: test
    - shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt install cadaver -y
        echo ${{ secrets.username }}
        
