# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
    - name: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: pip install
      run: |
        pip install -U pip
        pip install -U wheel setuptools 
        pip install -U bypy
    - name: config bypy
      run: |
        mkdir -p /home/runner/.bypy/
        echo -e "${{secrets.BYPY}}" >/home/runner/.bypy/bypy.json
        bypy info
    - name: Change Dir
      run: |
        mkdir upload
        cd upload
    - name: Set current date as env variable
      run: |
        echo "NOW=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        echo "PACKAGE7ZFILE=${{ env.NOW }}-${{ github.run_id }}.7z" >> $GITHUB_ENV
    - name: Package 
      run: 7z a "${{ env.PACKAGE7ZFILE }}" ./
#     - name: wget package
#       run: |
#         cat get.txt | xargs wget -q --show-progress --progress=bar:force:noscroll -c -P upload/ 
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./
        asset_name: "${{ env.PACKAGE7ZFILE }}"
    - name: upload by bypy
      run: |
        bypy -v upload ./"${{ env.PACKAGE7ZFILE }}"
    - name: finish
      run: |
        echo "ok!"
    
