# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: |
        pip install -U pip
        pip install -U wheel setuptools 
        pip install -U bypy
        mkdir -p /home/runner/.bypy/
        echo -e "${{secrets.BYPY}}" >/home/runner/.bypy/bypy.json
        bypy info
        wget https://github.com/skylot/jadx/releases/download/v1.2.0/jadx-gui-1.2.0-with-jre-win.zip
        bypy upload jadx-gui-1.2.0-with-jre-win.zip
    
